[package]
name = "rust-starter-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
env_logger = "0.9.1"
actix-web = "4"
diesel = { version="2.0.1", features=["postgres", "r2d2"] }
